### ISSUE TITLE
V6.0.0 Release Testing Checklist

### ISSUE THREAD

**Issue by Soyvolon** [Soyvolon/PartnerBot#11]
# Testing Checklist

A list of things to check before release.

### Setup

- [x] Non-donor basic setup
- [x]  Non-donor interactive setup
- [x] Donor level 1 interactive setup
- [x] Donor level 2 interactive setup
- [x] Donor level 3 interactive setup
- [x] Add custom embed
- [x] Remove custom embed
- [x] Edit custom embed
- [x] Add custom embed field
- [x] Edit custom embed field
- [x] Remove custom embed filed

### Utility

- [x] Invite command
- [x] Purge command

### Internal

- [x] Link counts are properly updated when messages are changed that have links in them.
- [x] Changes in donor status are updated properly
- [x] Channel verification service catches bad servers and disables them
- [x] Partner Sender sends extra embeds
- [x] Partner Sender sends extra message when an extra match is found
